/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package interviewcamp;

import java.util.Arrays;

public class Chapter3 {
	public static void main(String[] args) {
		System.out.println(Arrays.toString(binarySearch(new Integer[]{1, 2, 4, 6, 8, 10, 11, 13, 15, 20, 22}, 13)));
		System.out.println(Arrays.toString(binarySearchWithDuplicates(new Integer[]{1, 2, 4, 6, 8, 10, 11, 13, 13, 13, 13, 13, 15, 20, 22}, 13)));
		System.out.println((findIndex(new Integer[]{2, 3, 4, 6, 8}, 2)));
		System.out.println((binarySearchOrClosest(new Integer[]{1, 2, 4, 11, 13, 15, 20, 22}, 5)));
	}

	private static int findIndex(Integer[] a, int target) {
		int start = 0;
		int end = a.length;
		if (target <= a[0]) return 0;
		if (target >= a[a.length - 1]) return a.length;
		while (true) {
			int mid = start + (end - start) / 2;
			if (mid < a.length - 1 && a[mid] <= target && a[mid + 1] > target) {
				return mid + 1;
			} else if (a[mid] > target) {
				end = mid + 1;
			} else if (a[mid] < target) {
				start = mid - 1;
			}
		}
	}


	private static int[] binarySearch(Integer[] a, int target) {
		int start = 0;
		int end = a.length;
		while (true) {
			int middle = start + (end - start) / 2;
			if (a[middle] == target) {
				return new int[]{a[middle], middle};
			} else if (a[middle] > target) {
				end = middle;
			} else if (a[middle] < target) {
				start = middle;
			}
		}
	}


	private static int binarySearchOrClosest(Integer[] a, int target) {
		int start = 0;
		int end = a.length;
		Integer closest = null;
		while (end >= start) {
			int middle = start + (end - start) / 2;
			closest = getClosest(a, target, closest, middle);
			if (a[middle] == target) {
				return a[middle];
			} else if (a[middle] > target) {
				end = middle - 1;
			} else if (a[middle] < target) {
				start = middle + 1;
			}
		}
		return closest;
	}

	private static int getClosest(Integer[] a, int target, Integer closest, int middle) {
		if (closest == null) {
			return a[middle];
		}
		if (Math.abs(target - a[middle]) < Math.abs(target - closest)) {
			return a[middle];
		}
		return closest;
	}

	private static int[] binarySearchWithDuplicates(Integer[] a, int target) {
		int start = 0;
		int end = a.length;
		while (true) {
			int middle = start + (end - start) / 2;
			if (a[middle] > target
					|| (a[middle] == target && middle > 0 && a[middle - 1] == target)) {
				end = middle - 1;
			} else if (a[middle] == target) {
				return new int[]{a[middle], middle};
			} else if (a[middle] < target) {
				start = middle + 1;
			}
		}
	}
}
