/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package interviewcamp;

import java.util.Arrays;

public class Chapter3_and_4 {
	public static void main(String[] args) {
		System.out.println(Arrays.toString(binarySearch(new Integer[]{1, 2, 4, 6, 8, 10, 11, 13, 15, 20, 22}, 13)));
		System.out.println(Arrays.toString(binarySearchWithDuplicates(new Integer[]{1, 2, 4, 6, 8, 10, 11, 13, 13, 13, 13, 13, 15, 20, 22}, 13)));
		System.out.println((findIndex(new Integer[]{2, 3, 4, 6, 8}, 2)));
		System.out.println((binarySearchOrClosest(new Integer[]{1, 2, 4, 11, 13, 15, 20, 22}, 5)));
		System.out.println((findSmallestRotated(new Integer[]{4, 5, 6, 2, 3})));
		System.out.println((squareRoot(1234544444433234446L)));
		System.out.println(Arrays.toString(findPeak(new int[]{1, 3, 4, 5, 2})));

	}

	private static int[] findPeak(int[] a) {
		int start = 0, end = a.length - 1;
		while (true) {
			int mid = start + (end - start) / 2;
			if (mid > 0 && a[mid] > a[mid - 1] && a[mid] > a[mid + 1]) {
				return new int[]{a[mid], mid};
			} else if (a[mid] < a[mid + 1]) {
				start = mid + 1;
			} else {
				end = mid - 1;
			}
		}
	}

	private static long squareRoot(long target) {
		long low = 0, high = target / 2;
		long best = Integer.MAX_VALUE;
		while (high >= low) {
			long mid = low + (high - low) / 2;
			long square = mid * mid;
			if (Math.abs(square - target) < Math.abs(best * best - target)) {
				best = mid;
			}
			if (target < square) {
				high = mid - 1;
			} else if (target > square) {
				low = mid + 1;
			} else {
				return mid;
			}
		}
		return best;
	}

	private static int findSmallestRotated(Integer[] a) {
		int maxSecondGroup = a[a.length - 1];
		int low = 0, high = a.length / 2;
		while (true) {
			int mid = low + (high - low) / 2;
			int midVal = a[mid];
			if (mid > 0 && midVal < a[mid - 1]) {
				return a[mid];
			} else if (midVal > maxSecondGroup) {
				low = mid + 1;
			} else if (midVal < maxSecondGroup) {
				high = mid - 1;
			}
		}
	}

	private static int findIndex(Integer[] a, int target) {
		int start = 0;
		int end = a.length;
		if (target <= a[0]) return 0;
		if (target >= a[a.length - 1]) return a.length;
		while (true) {
			int mid = start + (end - start) / 2;
			if (mid < a.length - 1 && a[mid] <= target && a[mid + 1] > target) {
				return mid + 1;
			} else if (a[mid] > target) {
				end = mid + 1;
			} else if (a[mid] < target) {
				start = mid - 1;
			}
		}
	}


	private static int[] binarySearch(Integer[] a, int target) {
		int start = 0;
		int end = a.length;
		while (true) {
			int middle = start + (end - start) / 2;
			if (a[middle] == target) {
				return new int[]{a[middle], middle};
			} else if (a[middle] > target) {
				end = middle;
			} else if (a[middle] < target) {
				start = middle;
			}
		}
	}


	private static int binarySearchOrClosest(Integer[] a, int target) {
		int start = 0;
		int end = a.length;
		Integer closest = null;
		while (end >= start) {
			int middle = start + (end - start) / 2;
			closest = getClosest(a, target, closest, middle);
			if (a[middle] == target) {
				return a[middle];
			} else if (a[middle] > target) {
				end = middle - 1;
			} else if (a[middle] < target) {
				start = middle + 1;
			}
		}
		return closest;
	}

	private static int getClosest(Integer[] a, int target, Integer closest, int middle) {
		if (closest == null) {
			return a[middle];
		}
		if (Math.abs(target - a[middle]) < Math.abs(target - closest)) {
			return a[middle];
		}
		return closest;
	}

	private static int[] binarySearchWithDuplicates(Integer[] a, int target) {
		int start = 0;
		int end = a.length;
		while (true) {
			int middle = start + (end - start) / 2;
			if (a[middle] > target
					|| (a[middle] == target && middle > 0 && a[middle - 1] == target)) {
				end = middle - 1;
			} else if (a[middle] == target) {
				return new int[]{a[middle], middle};
			} else if (a[middle] < target) {
				start = middle + 1;
			}
		}
	}
}
