/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package interviewcamp;

import java.util.Arrays;
import java.util.Comparator;

public class Chapter1 {
	public static void main(String[] args) {
		System.out.println(Arrays.toString(duplicateEven(new Integer[]{1, 2, 5, 6, 8, null, null, null})));
		reverse("i live in a house");
		System.out.println(Arrays.toString(reverse(new int[]{1, 2, 3, 4, 5})));
		System.out.println(Arrays.toString(twoSum(new int[]{1, 2, 3, 4, 5}, 6)));
		System.out.println(Arrays.toString(arraySquares(new int[]{-4, -2, -1, 3, 5})));
		System.out.println(Arrays.toString(findLeastContinuousArrayToSort(new int[]{0, 2, 3, 1, 8, 6, 9})));
		System.out.println(Arrays.toString(rearrange(new int[]{4, 2, 0, 1, 0, 3, 0})));
		System.out.println(Arrays.toString(rearrange2(new int[]{4, 2, 0, 1, 0, 3, 0})));
		System.out.println(Arrays.toString(dutchflag(new int[]{1, 0, 1, 2, 1, 0, 1, 2}, 1)));
	}

	private static int[] dutchflag(int[] a, int pivot) {
		int lower = 0, upper = a.length - 1;
		int i = 0;
		while (i <= upper) {
			if (a[i] > pivot) {
				swap(a, i, upper--);

			} else if (a[i] < pivot) {
				swap(a, i, lower++);
			} else {
				i++;
			}

		}
		return a;
	}

	private static int[] rearrange(int[] a) {
		int border = 0;
		for (int i = 0; i < a.length; i++) {
			if (a[i] == 0) {
				swap(a, border, i);
				border++;
			}
		}
		return a;
	}

	private static void swap(int[] a, int i, int j) {
		int temp = a[j];
		a[j] = a[i];
		a[i] = temp;
	}

	private static int[] rearrange2(int[] a) {
		int border = a.length - 1;
		for (int i = a.length - 1; i >= 0; i--) {
			if (a[i] == 0) {
				swap(a, border, i);
				border--;
			}
		}
		return a;
	}

	private static int[] findLeastContinuousArrayToSort(int[] a) {
		int i = 0, j = a.length;
		boolean doneI = false, doneJ = false;
		while (!doneI && !doneJ) {
			if (Arrays.stream(Arrays.copyOfRange(a, i + 1, j)).mapToLong(b -> b).min().getAsLong() < a[i]) {
				doneI = true;
			} else {
				i++;
			}
			if (Arrays.stream(Arrays.copyOfRange(a, i, j - 1)).mapToLong(b -> b).max().getAsLong() > a[j - 1]) {
				doneJ = true;
			} else {
				j--;
			}
		}
		return Arrays.copyOfRange(a, i, j);
	}

	private static double[] arraySquares(int[] a) {
		int i = 0, j = a.length - 1;
		double[] b = new double[a.length];
		int x = b.length - 1;
		while (i <= j) {
			if (Math.pow(a[i], 2) >= Math.pow(a[j], 2)) {
				b[x--] = Math.pow(a[i], 2);
				i++;
			}
			if (Math.pow(a[i], 2) < Math.pow(a[j], 2)) {
				b[x--] = Math.pow(a[j], 2);
				j--;
			}
		}
		return b;
	}

	private static int[] twoSum(int[] a, int sum) {
		int i = 0, j = a.length - 1;
		while (i <= j) {
			if (a[i] + a[j] < sum) {
				i++;
			} else if (a[i] + a[j] > sum) {
				j++;
			} else {
				return new int[]{a[i], a[j]};
			}
		}
		throw new IllegalArgumentException();
	}

	private static void reverse(String string) {
		int end = string.length();
		for (int i = string.length() - 1; i >= 0; i--) {
			if (string.charAt(i) == ' ' || i == 0) {
				System.out.print(string.substring(i + (i == 0 ? 0 : 1), end) + " ");
				end = i;
			}
		}
	}

	private static int[] reverse(int[] elements) {
		for (int i = 0; i <= elements.length / 2; i++) {
			swap(elements, elements.length - i - 1, i);
		}
		return elements;
	}

	private static Integer[] duplicateEven(Integer[] ints) {
		int end = ints.length - 1;
		for (int i = ints.length - 1; i >= 0; i--) {
			if (ints[i] != null) {
				ints[end--] = ints[i];
				if (ints[i] % 2 == 0) {
					ints[end--] = ints[i];
				}
			}
		}
		return ints;
	}


	public String[] reorderLogFiles(String[] logs) {
		int start = 0, end = logs.length - 1, i = 0;
		while (i <= end) {
			if (isDigit(logs[i])) {
				swap(logs, i, end);
				end--;
			} else {
				start++;
				i++;
			}
		}
		Arrays.sort(logs, 0, start, Comparator.comparing(b -> ((String) b).split(" ")[1]).thenComparing
				(b -> ((String) b).split(" ")[0]));


		return logs;
	}

	static void swap(String[] a, int i, int j) {
		String temp = a[j];
		a[j] = a[i];
		a[i] = temp;
	}

	public static boolean isDigit(String s) {

		char c = s.split(" ")[1].charAt(0);
		return (c == '1' || c == '2' || c == '3' || c == '4' || c == '5' || c == '6' || c == '7' || c == '8' || c == '9' || c == '0');
	}
}
