/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package interviewcamp;

import java.util.Arrays;
import java.util.HashMap;
import java.util.Map;

public class Chapter2 {
	public static void main(String[] args) {
		System.out.println(Arrays.toString(kadaneMaximumSubSubarray(new Integer[]{1, 2, -1, 2, -3, 2, -5})));
		System.out.println(Arrays.toString(twoNumersSum(new int[]{1, 3, 2, 5, 2}, 8)));
		System.out.println(Arrays.toString(subarraySum(new int[]{1, 3, 0, 5, 2}, 8)));
		System.out.println(longestUnique("whatwhywhere"));
		System.out.println(Arrays.toString(sumsToZeroSubarray(new int[]{2, 4, -2, 1, -3, 5, -3})));
		System.out.println(Arrays.toString(sumsToXSubarray(new int[]{2, 4, -2, 1, -3, 5, -3}, 5)));
	}

	private static int[] sumsToXSubarray(int[] a, int target) {
		int[] b = new int[a.length];
		int sum = 0;
		for (int i = 0; i < a.length; i++) {
			sum = a[i] + sum;
			b[i] = sum;
		}
		Map<Integer, Integer> map = new HashMap<>();
		for (int i = 0; i < b.length; i++) {
			if (b[i] == target) {
				return Arrays.copyOfRange(a, 0, i + 1);

			}
			if (map.containsKey(b[i] - target)) {
				return Arrays.copyOfRange(a, map.get(b[i] - target), i);
			}

		}
		throw new IllegalArgumentException();
	}

	private static int[] sumsToZeroSubarray(int[] a) {
		int[] b = new int[a.length];
		int sum = 0;
		for (int i = 0; i < a.length; i++) {
			sum = a[i] + sum;
			b[i] = sum;
		}
		Map<Integer, Integer> seen = new HashMap<>();
		for (int i = 0; i < b.length; i++) {
			if (b[i] == 0) {
				return Arrays.copyOfRange(a, 0, i + 1);
			}
			if (seen.containsKey(b[i])) {
				return Arrays.copyOfRange(a, seen.get(b[i]) + 1, i + 1);
			}
			seen.put(b[i], i);
		}
		throw new IllegalArgumentException();
	}

	private static int longestUnique(String string) {
		int start = 0, end = 1;
		int max = -1;
		Map<Character, Integer> positions = new HashMap<>();
		while (end < string.length()) {
			if (positions.containsKey(string.charAt(end - 1))) {
				start = positions.get(string.charAt(end - 1));
			}
			String substring = string.substring(start, end);
			max = Math.max(substring.length(), max);
			positions.put(string.charAt(end - 1), end);
			end++;
		}
		return max;
	}

	private static int[] twoNumersSum(int[] a, int sum) {
		HashMap<Integer, Integer> ints = new HashMap<>();
		for (int aa : a) {
			if (ints.containsKey(aa)) {
				return new int[]{aa, ints.get(aa)};
			}
			ints.put(8 - aa, aa);

		}
		throw new IllegalArgumentException();
	}

	private static int[] subarraySum(int[] a, int target) {
		int start = 0, end = 1;
		while (true) {
			int currentSum = Arrays.stream(Arrays.copyOfRange(a, start, end)).sum();
			if (currentSum > target) {
				start++;
			} else if (currentSum < target) {
				end++;
			} else {
				return new int[]{start, end, currentSum};
			}
		}
	}

	private static int[] kadaneMaximumSubSubarray(Integer[] a) {
		int maxSumSoFar = Integer.MIN_VALUE;
		int endingHere = 0;
		for (int i = 0; i < a.length; i++) {
			endingHere += a[i];
			if (endingHere < 0) {
				endingHere = a[i];
			}
			if (maxSumSoFar < endingHere) {
				maxSumSoFar = endingHere;
			}
		}
		return new int[]{maxSumSoFar};
	}
}
