/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package interviewcamp;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;

import org.apache.commons.collections4.ListUtils;

public class Chapter6 {
	public static void main(String[] args) {
		System.out.println(fibonacci(19, new HashMap<>()));
		System.out.println(fibonacci(16));
		System.out.println(x_pow_n(2, 10));
		System.out.println(x_pow_n2(2, 10));
		permutations(new int[]{1, 2, 3}, new int[0], 0);
		System.out.println();
		System.out.println();
		System.out.println();
		System.out.println();
		mnemonics("23", new char[0], 2);
		System.out.println();
		System.out.println();
		System.out.println();
		System.out.println();
		permutations2(new int[]{1, 2, 3}, new int[0], 0);
		System.out.println();
		System.out.println();
		System.out.println();
		System.out.println();
		System.out.println("+++++++++++++++++++");
		coins(Arrays.asList(1, 2, 5), 5, 0, new ArrayList<>());
		System.out.println();
		System.out.println();
		System.out.println();
		System.out.println();
		System.out.println("+++++++++++++++++++");
		System.out.println(exists(new int[][]{
				new int[]{0, 0, 0, 1},
				new int[]{0, 1, 0, 1},
				new int[]{1, 0, 0, 1},
				new int[]{1, 1, 0, 0}}, 0, 0, new HashMap<>()));

		System.out.println(breakLetters("ilikemangotango", Set.of("gotango", "i", "like", "man", "tan")));
	}

	private static List<String> breakLetters(String letters, Set<String> dictionary) {
		if (dictionary.contains(letters)) {
			return Collections.singletonList(letters);
		}
		for (int i = 0; i < letters.length(); i++) {
			if (dictionary.contains(letters.substring(0, i + 1))) {
				List<String> recursiveResult = breakLetters(letters.substring(i + 1), dictionary);
				if (!recursiveResult.isEmpty()) {
					return ListUtils.union(Collections.singletonList(letters.substring(0, i + 1)), recursiveResult);
				}
			}
		}
		return new ArrayList<>();
	}

	static class Pos {
		int x, y;

		public Pos(int x, int y) {
			this.x = x;
			this.y = y;
		}

		@Override
		public boolean equals(Object o) {
			if (this == o) return true;
			if (o == null || getClass() != o.getClass()) return false;
			Pos pos = (Pos) o;
			return x == pos.x &&
					y == pos.y;
		}

		@Override
		public int hashCode() {
			return Objects.hash(x, y);
		}
	}

	enum Status {
		PUSHED_CHILDREN,
		VISITING,
		UNVISITED;
	}

	private static boolean exists(int[][] a, int xPos, int yPos, Map<Pos, Status> memo) {

//		if (memo.containsKey(new Pos(xPos, yPos)) && memo.get(new Pos(xPos, yPos)) != Status.UNVISITED) {
//			return false;
//		}
//		if (xPos < 0 || yPos < 0) {
//			return false;
//		}
		if (xPos == 3 && yPos == 3) {
			return true;
		}
		boolean existsAround = false;
		if (isPath(a, xPos + 1, yPos) && memo.get(new Pos(xPos + 1, yPos)) != Status.VISITING) {
			memo.put(new Pos(xPos + 1, yPos), Status.VISITING);
			existsAround = exists(a, xPos + 1, yPos, memo);
		}
		if (isPath(a, xPos, yPos + 1) && memo.get(new Pos(xPos, yPos + 1)) != Status.VISITING) {
			memo.put(new Pos(xPos, yPos + 1), Status.VISITING);
			existsAround |= exists(a, xPos, yPos + 1, memo);
		}
		if (isPath(a, xPos - 1, yPos) && memo.get(new Pos(xPos - 1, yPos)) != Status.VISITING) {
			memo.put(new Pos(xPos - 1, yPos), Status.VISITING);
			existsAround |= exists(a, xPos - 1, yPos, memo);
		}
		if (isPath(a, xPos, yPos - 1) && memo.get(new Pos(xPos, yPos - 1)) != Status.VISITING) {
			memo.put(new Pos(xPos, yPos - 1), Status.VISITING);
			existsAround |= exists(a, xPos - 1, yPos, memo);
		}
		return existsAround;
	}

	static boolean isPath(int[][] a, int x, int y) {
		if (x < 0 || y < 0 || y >= a.length || x >= a[0].length) {
			return false;
		}
		return a[y][x] == 0;
	}

	private static void coins(List<Integer> coins, int target, int startIndex, List<Integer> aux) {
		if (aux.stream().mapToInt(a -> a).sum() > target) {
			return;
		}
		if (aux.stream().mapToInt(a -> a).sum() == target) {
			System.out.println(Arrays.toString(aux.toArray()));
			return;
		}
		for (int i1 = startIndex; i1 < coins.size(); i1++) {
			int i = coins.get(i1);
			ArrayList<Integer> aux1 = new ArrayList<>(aux);
			aux1.add(i);
			coins(coins, target, i1, aux1);
		}
	}

	private static void mnemonics(String a, char[] aux, int aLen) {
		if (aux.length == aLen) {
			System.out.println(new String(aux));
			return;
		}
		if (a.length() != 0) {
			for (char c : getLetters(Integer.valueOf(a.substring(0, 1)))) {
				char[] newAux = Arrays.copyOf(aux, aux.length + 1);
				newAux[newAux.length - 1] = c;
				mnemonics(a.substring(1), newAux, aLen);
			}
		}
	}

	private static void permutations(int[] a, int[] aux, int from) {
		System.out.println(Arrays.toString(aux));
		for (int i = from; i < a.length; i++) {
			int[] copyOfRange = Arrays.copyOfRange(a, from + 1, a.length);
			int[] newAux = Arrays.copyOf(aux, aux.length + 1);
			newAux[newAux.length - 1] = a[i];
			permutations(copyOfRange, newAux, i);
		}
	}

	private static void permutations2(int[] a, int[] aux, int from) {
		if (aux.length == 2) {
			System.out.println(Arrays.toString(aux));
			return;
		}
		for (int i = from; i < a.length; i++) {
			int[] j = new int[a.length - 1];
			int aaa = 0;
			for (int aa = 0; aa < a.length; aa++) {
				if (aa != i) {
					j[aaa++] = a[aa];
				}
			}

			int[] newAux = Arrays.copyOf(aux, aux.length + 1);
			newAux[newAux.length - 1] = a[i];
			permutations2(j, newAux, i);
		}
	}

	private static int x_pow_n(int i, int n) {
		if (n == 0) return 1;
		if (n == 1) return i;
		return x_pow_n(i, n - 1) * i;
	}


	private static int x_pow_n2(int i, int n) {
		int result = 1;
		for (int j = 0; j < n; j++) {
			result *= i;
		}
		return result;
	}

	private static int fibonacci(int i, Map<Integer, Integer> memo) {
		if (i <= 2) {
			return 1;
		}
		if (memo.containsKey(i)) {
			return memo.get(i);
		}
		int result = fibonacci(i - 1, memo) + fibonacci(i - 2, memo);
		memo.put(i, result);
		return result;
	}


	private static int fibonacci(int i) {
		int prev1 = 1;
		int prev2 = 1;
		int result = 0;
		for (int j = 0; j <= i; j++) {
			result = prev1 + prev2;
			prev2 = prev1;
			prev1 = result;
		}
		return result;
	}


	public static char[] getLetters(int digit) {
		switch (digit) {
			case 0:
				return new char[]{};
			case 1:
				return new char[]{};
			case 2:
				return new char[]{'a', 'b', 'c'};
			case 3:
				return new char[]{'d', 'e', 'f'};
			case 4:
				return new char[]{'g', 'h', 'i'};
			case 5:
				return new char[]{'j', 'k', 'l'};
			case 6:
				return new char[]{'m', 'n', 'o'};
			case 7:
				return new char[]{'p', 'q', 'r', 's'};
			case 8:
				return new char[]{'t', 'u', 'v'};
			case 9:
				return new char[]{'w', 'x', 'y', 'z'};
		}
		throw new IllegalArgumentException("Invalid Digit " + digit);
	}


}
