/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package interviewcamp;

import java.util.Arrays;
import java.util.Comparator;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.stream.Collectors;

public class Chapter7 {

	public static void main(String[] args) {

		Node n1 = new Node();
		Node n2 = new Node();
		Node n3 = new Node();
		Node n4 = new Node();
		Node n5 = new Node();
		Node n6 = new Node();
		Node n7 = new Node();
		Node n8 = new Node();
		Node n9 = new Node();
		n1.next = n2;
		n2.next = n3;
		n3.next = n4;
		n4.next = n5;
		n5.next = n6;
		n6.next = n7;
		n7.next = n8;
		n8.next = n9;
		n9.next = n4;


		System.out.println(hasCycle(n1));
		System.out.println(hasCycle2(n1));
		System.out.println(cycleLen(n1));

		n9.next = null;
		System.out.println(median(n1));

		LinkedHashTable t = new LinkedHashTable();
		t.write("1", "1");
		t.write("2", "2");
		t.write("3", "3");
		t.write("4", "4");
		t.write("5", "5");

		t.read("2");

		System.out.println(t.getLast());
		System.out.println(longestSubstrContainingAll(
				"a set of words that is complete in itself typically containing a subject and predicate conveying a statement question "
						+ "exclamation or command and consisting of a main clause and sometimes one or more subordinate clauses",
				Arrays.asList("and", "of", "one")));

	}

	private static String longestSubstrContainingAll(String sentence, List<String> targetWords) {

		Map<String, Integer> results = new HashMap<>();
		String[] wordsArray = sentence.split(" ");
		HashMap<String, Integer> map = new HashMap<>();

		for (int i = 0; i < wordsArray.length; i++) {
			if (targetWords.contains(wordsArray[i])) {
				map.put(wordsArray[i], i);
			}

			if (targetWords.stream().allMatch(map::containsKey)) {
				int min = map.values().stream().mapToInt(a -> a).min().getAsInt();
				int max = map.values().stream().mapToInt(a -> a).max().getAsInt();
				results.put(Arrays.stream(Arrays.copyOfRange(wordsArray, min, max + 1)).collect(Collectors.joining(" ")),
						max - min
				);
			}
		}
		return results.entrySet().stream().sorted(Comparator.comparing(Map.Entry::getValue)).map(a->a.getKey()).findFirst().get();
	}

	static class LinkedHashTable {
		LinkedHashMap<String, String> linkedHashMap = new LinkedHashMap<>();

		String read(String key) {
			String value = linkedHashMap.get(key);
			linkedHashMap.remove(key);
			linkedHashMap.put(key, value);
			return key;
		}

		void write(String key, String value) {
			linkedHashMap.put(key, value);
		}

		String getLast() {
			return linkedHashMap.get(0);
		}
	}

	private static boolean hasCycle(Node n1) {
		Node current = n1;
		Set<Node> seen = new HashSet<>();
		while (current != null) {
			if (seen.contains(current)) {
				return true;
			}
			seen.add(current);
			current = current.next;
		}
		return false;
	}

	private static boolean hasCycle2(Node n1) {
		Node slow = n1, fast = n1.next.next;
		while (slow != null && fast != null) {
			if (slow == fast) {
				return true;
			}
			slow = slow.next;
			fast = fast.next;
			if (fast != null) {
				fast = fast.next;
			}
		}

		return false;
	}

	private static int median(Node head) {
		Node slow = head, fast = head.next.next;
		int i = 0;
		while (true) {
			i++;
			if (fast == null) {
				return i;
			}

			slow = slow.next;
			fast = fast.next;
			if (fast != null) {
				fast = fast.next;
			}

		}

	}

	private static int cycleLen(Node n1) {
		Node slow = n1, fast = n1.next.next;
		while (slow != null && fast != null) {
			if (slow == fast) {
				break;
			}
			slow = slow.next;
			fast = fast.next;
			if (fast != null) {
				fast = fast.next;
			}
		}
		int n = 0;
		if (slow == fast) {
			slow = slow.next;

			while (slow != fast) {
				slow = slow.next;
				n++;
			}
		}

		return n;
	}

	static class Node {
		Node next;

	}

}
